package com.edgeos.launcher;
import android.accessibilityservice.AccessibilityService;import android.graphics.Color;import android.graphics.PixelFormat;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import android.content.*;
public class AssistiveService extends AccessibilityService{
 WindowManager wm;View bubble;LinearLayout panel;Handler h=new Handler();int flags=WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS;
 public void onServiceConnected(){super.onServiceConnected();if(Settings.canDrawOverlays(this))showBubble();}
 int type(){return Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE;}
 void showBubble(){if(bubble!=null)return;wm=(WindowManager)getSystemService(WINDOW_SERVICE);TextView b=Ui.text(this,"◉",24,Color.WHITE);b.setBackground(Ui.bg(0xCC20242D,80));bubble=b;WindowManager.LayoutParams p=new WindowManager.LayoutParams(Ui.dp(this,58),Ui.dp(this,58),type(),flags,PixelFormat.TRANSLUCENT);p.gravity=Gravity.RIGHT|Gravity.CENTER_VERTICAL;p.x=12;b.setOnTouchListener(new View.OnTouchListener(){float sy,dy;public boolean onTouch(View v,android.view.MotionEvent e){if(e.getAction()==0){sy=e.getRawY();dy=p.y;return true;}if(e.getAction()==2){p.y=(int)(dy+e.getRawY()-sy);wm.updateViewLayout(b,p);return true;}if(e.getAction()==1){showPanel();return true;}return true;}});wm.addView(b,p);}
 void showPanel(){if(panel!=null){wm.removeView(panel);panel=null;return;}panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(18,18,18,18);panel.setBackground(Ui.bg(0xEE1B1D24,34));String[] a={"‹ Back","⌂ Home","▣ Recents","⚡ Quick Settings","☰ Notifications","🔒 Lock Screen","▣ Screenshot","⚙ Settings"};for(String s:a){Button b=Ui.pill(this,s);b.setOnClickListener(v->act(((Button)v).getText().toString()));panel.addView(b,new LinearLayout.LayoutParams(Ui.dp(this,190),Ui.dp(this,48)));}WindowManager.LayoutParams p=new WindowManager.LayoutParams(Ui.dp(this,210),-2,type(),flags,PixelFormat.TRANSLUCENT);p.gravity=Gravity.RIGHT|Gravity.CENTER_VERTICAL;p.x=Ui.dp(this,78);wm.addView(panel,p);}
 void act(String s){if(s.contains("Back"))performGlobalAction(GLOBAL_ACTION_BACK);else if(s.contains("Home"))performGlobalAction(GLOBAL_ACTION_HOME);else if(s.contains("Recents"))performGlobalAction(GLOBAL_ACTION_RECENTS);else if(s.contains("Quick"))performGlobalAction(GLOBAL_ACTION_QUICK_SETTINGS);else if(s.contains("Notifications"))performGlobalAction(GLOBAL_ACTION_NOTIFICATIONS);else if(s.contains("Lock")){if(Build.VERSION.SDK_INT>=28)performGlobalAction(GLOBAL_ACTION_LOCK_SCREEN);else startActivity(new Intent(Settings.ACTION_SECURITY_SETTINGS).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));}else if(s.contains("Settings"))startActivity(new Intent(Settings.ACTION_SETTINGS).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));if(panel!=null){wm.removeView(panel);panel=null;}}
 public void onAccessibilityEvent(android.view.accessibility.AccessibilityEvent e){} public void onInterrupt(){} public void onDestroy(){try{if(bubble!=null)wm.removeView(bubble);if(panel!=null)wm.removeView(panel);}catch(Exception ignored){}super.onDestroy();}
}
