package com.edgeos.launcher;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;
public class HomeActivity extends Activity{
 LinearLayout root,pages,dock; HorizontalScrollView pager; ArrayList<AppInfo> apps; int pageSize=20; float downX; boolean dark=true;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.BLACK);dark=LauncherPrefs.dark(this);build();}
 TextView tv(String s,float z){return Ui.text(this,s,z,Color.WHITE);}
 void build(){apps=AppRepository.load(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,16),Ui.dp(this,18),Ui.dp(this,16),Ui.dp(this,12));root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{dark?0xFF111827:0xFFE8ECF2,dark?0xFF27324A:0xFFC7D2E4}));setContentView(root);
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView date=tv("Monday, 7 September",14);top.addView(date,new LinearLayout.LayoutParams(0,Ui.dp(this,36),1));Button search=Ui.pill(this,"⌕");top.addView(search,new LinearLayout.LayoutParams(Ui.dp(this,58),Ui.dp(this,48)));search.setOnClickListener(v->startActivity(new Intent(this,SearchActivity.class)));root.addView(top);
  TextView clock=tv(new java.text.SimpleDateFormat("HH:mm",java.util.Locale.getDefault()).format(new Date()),52);clock.setTypeface(null,android.graphics.Typeface.BOLD);root.addView(clock,new LinearLayout.LayoutParams(-1,Ui.dp(this,80)));new Handler().postDelayed(new Runnable(){public void run(){clock.setText(new java.text.SimpleDateFormat("HH:mm",java.util.Locale.getDefault()).format(new Date()));new Handler().postDelayed(this,1000);}},1000);
  pager=new HorizontalScrollView(this);pager.setHorizontalScrollBarEnabled(false);pager.setOverScrollMode(View.OVER_SCROLL_NEVER);pages=new LinearLayout(this);pages.setOrientation(LinearLayout.HORIZONTAL);pager.addView(pages,new HorizontalScrollView.LayoutParams(-1,-1));root.addView(pager,new LinearLayout.LayoutParams(-1,0,1));renderPages();
  dock=new LinearLayout(this);dock.setGravity(Gravity.CENTER);dock.setPadding(8,8,8,8);dock.setBackground(Ui.bg(0x883A414F,Ui.dp(this,28)));root.addView(dock,new LinearLayout.LayoutParams(-1,Ui.dp(this,76)));renderDock();
 }
 void renderPages(){pages.removeAllViews();int count=Math.max(1,(apps.size()+pageSize-1)/pageSize);for(int p=0;p<count;p++){LinearLayout grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);grid.setPadding(4,4,4,4);for(int r=0;r<5;r++){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER);for(int c=0;c<4;c++){int idx=p*20+r*4+c;FrameLayout cell=new FrameLayout(this);cell.setPadding(4,4,4,4);if(idx<apps.size())cell.addView(appView(apps.get(idx)));row.addView(cell,new LinearLayout.LayoutParams(0,0,1));}grid.addView(row,new LinearLayout.LayoutParams(-1,0,1));}pages.addView(grid,new LinearLayout.LayoutParams(-1,-1));}}
 View appView(AppInfo a){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);ImageView iv=new ImageView(this);iv.setImageDrawable(a.icon);box.addView(iv,new LinearLayout.LayoutParams(-1,0,1));TextView t=tv(a.label,10);t.setSingleLine(true);t.setEllipsize(android.text.TextUtils.TruncateAt.END);box.addView(t,new LinearLayout.LayoutParams(-1,Ui.dp(this,18)));box.setOnClickListener(v->launch(a));box.setOnLongClickListener(v->{showFolderMenu(a);return true;});return box;}
 void showFolderMenu(AppInfo a){PopupMenu m=new PopupMenu(this,root);m.getMenu().add("Buka");m.getMenu().add("Info aplikasi");m.setOnMenuItemClickListener(x->{if(x.getTitle().toString().startsWith("Buka"))launch(a);else try{startActivity(new Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS,android.net.Uri.parse("package:"+a.pkg)));}catch(Exception e){}return true;});m.show();}
 void renderDock(){dock.removeAllViews();int n=Math.min(4,apps.size());for(int i=0;i<n;i++){ImageButton b=new ImageButton(this);b.setImageDrawable(apps.get(i).icon);b.setBackgroundColor(Color.TRANSPARENT);final AppInfo a=apps.get(i);b.setOnClickListener(v->launch(a));dock.addView(b,new LinearLayout.LayoutParams(0,-1,1));}Button lib=Ui.pill(this,"•••");lib.setOnClickListener(v->startActivity(new Intent(this,AppLibraryActivity.class)));dock.addView(lib,new LinearLayout.LayoutParams(Ui.dp(this,62),-1));}
 void launch(AppInfo a){Intent i=getPackageManager().getLaunchIntentForPackage(a.pkg);if(i!=null)startActivity(i);}
 @Override protected void onResume(){super.onResume();if(root!=null){apps=AppRepository.load(this);renderPages();renderDock();}}
}
