plugins { id 'com.android.application' }

android {
    namespace 'com.edgeos.launcher'
    compileSdk 35

    defaultConfig {
        applicationId 'com.edgeos.launcher'
        minSdk 27
        targetSdk 35
        versionCode 10
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
