plugins { id 'com.android.application' }

android {
    namespace 'com.edgeos.launcher'
    compileSdk 34
    defaultConfig {
        applicationId 'com.edgeos.launcher'
        minSdk 27
        targetSdk 34
        versionCode 100
        versionName '1.0.0-final'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes {
        debug { signingConfig signingConfigs.debug; minifyEnabled false }
        release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' }
    }
}
